services:
  ingress:
    container_name: ingress
    build:
      context: .
      dockerfile: ./devops/configs/ingress/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    networks:
      - main

  web:
    container_name: web
    build:
      context: .
      dockerfile: /devops/configs/web/Dockerfile
    networks:
      - main

  backend:
    container_name: backend
    build:
      context: ./devops/configs/backend
      dockerfile: Dockerfile
    networks:
      - main

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB: postgres_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - main

volumes:
  pgdata:
    driver: local

networks:
  main:
    driver: bridge