-- AlterTable
ALTER TABLE "dev"."User" ALTER COLUMN "phone" DROP NOT NULL,
ALTER COLUMN "access_token" DROP NOT NULL,
ALTER COLUMN "lastip" DROP NOT NULL,
ALTER COLUMN "lastlogin" DROP NOT NULL,
ALTER COLUMN "refresh_token" DROP NOT NULL,
ALTER COLUMN "updated_at" DROP NOT NULL;
